#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaTec
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TiendaTec")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::TiendaTec.Properties.Settings.Default.TiendaTecConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarCategoriaProducto")]
		public int ActualizarCategoriaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> claveCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string nombreCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string descripcionCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), claveCategoria, nombreCategoria, descripcionCategoria, message);
			message = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BorrarCategoriaProducto")]
		public int BorrarCategoriaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> claveCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), claveCategoria, message);
			message = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarCategoriaProducto")]
		public int InsertarCategoriaProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string nombreCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string descripcionCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreCategoria, descripcionCategoria, message);
			message = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCategoriaProductoPorID")]
		public ISingleResult<MostrarCategoriaProductoPorIDResult> MostrarCategoriaProductoPorID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> claveCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), claveCategoria);
			return ((ISingleResult<MostrarCategoriaProductoPorIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarCategoriaProducto")]
		public ISingleResult<MostrarCategoriaProductoResult> MostrarCategoriaProducto()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarCategoriaProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarEmpleado")]
		public int ActualizarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpleados", DbType="Int")] System.Nullable<int> idEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(19)")] string rfcEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string telefonoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string puestoTrabajo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaContratacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleados, rfcEmpleados, nombreEmpleados, telefonoEmpleado, correoEmpleado, fechaNacimiento, puestoTrabajo, fechaContratacion, message);
			message = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.BorrarEmpleado")]
		public int BorrarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEmpleados", DbType="Int")] System.Nullable<int> idEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleados, message);
			message = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarEmpleado")]
		public int InsertarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(19)")] string rfcEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreEmpleados, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string telefonoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string puestoTrabajo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fechaContratacion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rfcEmpleados, nombreEmpleados, telefonoEmpleado, correoEmpleado, fechaNacimiento, puestoTrabajo, fechaContratacion, message);
			message = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MostrarEmpleado")]
		public ISingleResult<MostrarEmpleadoResult> MostrarEmpleado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<MostrarEmpleadoResult>)(result.ReturnValue));
		}
	}
	
	public partial class MostrarCategoriaProductoPorIDResult
	{
		
		private int _claveCategoria;
		
		private string _nombreCategoria;
		
		private string _descripcionCategoria;
		
		private System.DateTime _fechaCreacionCategorias;
		
		public MostrarCategoriaProductoPorIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_claveCategoria", DbType="Int NOT NULL")]
		public int claveCategoria
		{
			get
			{
				return this._claveCategoria;
			}
			set
			{
				if ((this._claveCategoria != value))
				{
					this._claveCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCategoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombreCategoria
		{
			get
			{
				return this._nombreCategoria;
			}
			set
			{
				if ((this._nombreCategoria != value))
				{
					this._nombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionCategoria", DbType="VarChar(MAX)")]
		public string descripcionCategoria
		{
			get
			{
				return this._descripcionCategoria;
			}
			set
			{
				if ((this._descripcionCategoria != value))
				{
					this._descripcionCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacionCategorias", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacionCategorias
		{
			get
			{
				return this._fechaCreacionCategorias;
			}
			set
			{
				if ((this._fechaCreacionCategorias != value))
				{
					this._fechaCreacionCategorias = value;
				}
			}
		}
	}
	
	public partial class MostrarCategoriaProductoResult
	{
		
		private int _claveCategoria;
		
		private string _nombreCategoria;
		
		private string _descripcionCategoria;
		
		private System.DateTime _fechaCreacionCategorias;
		
		public MostrarCategoriaProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_claveCategoria", DbType="Int NOT NULL")]
		public int claveCategoria
		{
			get
			{
				return this._claveCategoria;
			}
			set
			{
				if ((this._claveCategoria != value))
				{
					this._claveCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCategoria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nombreCategoria
		{
			get
			{
				return this._nombreCategoria;
			}
			set
			{
				if ((this._nombreCategoria != value))
				{
					this._nombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionCategoria", DbType="VarChar(MAX)")]
		public string descripcionCategoria
		{
			get
			{
				return this._descripcionCategoria;
			}
			set
			{
				if ((this._descripcionCategoria != value))
				{
					this._descripcionCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacionCategorias", DbType="DateTime NOT NULL")]
		public System.DateTime fechaCreacionCategorias
		{
			get
			{
				return this._fechaCreacionCategorias;
			}
			set
			{
				if ((this._fechaCreacionCategorias != value))
				{
					this._fechaCreacionCategorias = value;
				}
			}
		}
	}
	
	public partial class MostrarEmpleadoResult
	{
		
		private int _IdEmpleados;
		
		private string _rfcEmpleados;
		
		private string _nombreEmpleados;
		
		private string _telefonoEmpleado;
		
		private string _correoEmpleado;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
		private string _puestoTrabajo;
		
		private System.DateTime _fechaContratacion;
		
		public MostrarEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEmpleados", DbType="Int NOT NULL")]
		public int IdEmpleados
		{
			get
			{
				return this._IdEmpleados;
			}
			set
			{
				if ((this._IdEmpleados != value))
				{
					this._IdEmpleados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rfcEmpleados", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string rfcEmpleados
		{
			get
			{
				return this._rfcEmpleados;
			}
			set
			{
				if ((this._rfcEmpleados != value))
				{
					this._rfcEmpleados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpleados", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombreEmpleados
		{
			get
			{
				return this._nombreEmpleados;
			}
			set
			{
				if ((this._nombreEmpleados != value))
				{
					this._nombreEmpleados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoEmpleado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefonoEmpleado
		{
			get
			{
				return this._telefonoEmpleado;
			}
			set
			{
				if ((this._telefonoEmpleado != value))
				{
					this._telefonoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correoEmpleado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string correoEmpleado
		{
			get
			{
				return this._correoEmpleado;
			}
			set
			{
				if ((this._correoEmpleado != value))
				{
					this._correoEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this._fechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puestoTrabajo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string puestoTrabajo
		{
			get
			{
				return this._puestoTrabajo;
			}
			set
			{
				if ((this._puestoTrabajo != value))
				{
					this._puestoTrabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaContratacion", DbType="DateTime NOT NULL")]
		public System.DateTime fechaContratacion
		{
			get
			{
				return this._fechaContratacion;
			}
			set
			{
				if ((this._fechaContratacion != value))
				{
					this._fechaContratacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
